# Generated by Django 3.1 on 2020-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('beds', models.IntegerField()),
                ('baths', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sq_ft', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city_state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
