# Generated by Django 3.1 on 2020-08-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sq_ft',
            field=models.CharField(max_length=20),
        ),
    ]
