# Generated by Django 3.1 on 2020-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20200828_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_credit',
            field=models.CharField(default='Weichert, Realtors', max_length=200),
        ),
    ]
