# Generated by Django 3.1 on 2020-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_listing_photo_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sq_ft',
            field=models.IntegerField(),
        ),
    ]
