# Generated by Django 3.1 on 2020-10-05 19:19

from django.db import migrations, models
import django.utils.timezone
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20201005_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='youssef-real-estate'), upload_to=''),
            preserve_default=False,
        ),
    ]
